server:
  port: 8667
  
eureka:
  instance:
    prefer-ip-address: true  
  client:
    service-url:
      default-zone: http://127.0.0.1:8761/eureka  
      
spring:
  application:
    name: db-service 